# Site settings
title: "Bersam Karbasion"
description: "This is Bersam Karabsion's personal homepage."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Bersam Karbasion"
resume_title:                   "Master Student|Full Stack Developer"
resume_contact_email:           "bersam@bersam.org"
# resume_contact_telephone:       ""
resume_contact_address:         "Munich, Germany"
resume_header_contact_info:     "Munich, Germany • bersam@bersam.org"
display_header_contact_info:    "true"
resume_header_intro: "<p>My name is Bersam Karbasion (pronounced as [ber sa:m] in English and written as برسام کرباسیون in Persian). I was born in Iran and have been living in Germany since 2019. I earned my Bachelor of Science degree in Computer Science from Sheikh Bahaei University.</br>Currently, I am employed as an Engineering Manager at Personio, based in the beautiful city of Munich. Over the past 10 years, I have collaborated with well-known companies in the IT industry, improving my software engineering and management abilities. I take pleasure in participating in open-source projects and utilizing them in my daily life and work.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bersam"
  resume_twitter_url:           "http://twitter.com/bersamk"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/bersam"
  resume_instagram_url:         "http://instagram.com/bersamrocks"
  resume_website_url:           "http://bersam.org"
  resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
